title: Lebin Li's Homepage
page-top-title: Lebin Li
top-section-bg-text: Intelligence Science and Technology
home-subtitle: Lebin Li&ensp;|&ensp;李乐彬
copyright-text: '&copy; Lebin Li 2026. All Rights Reserved.'
